apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sheruchutanku/sheru.git
    targetRevision: HEAD
    path: argocdmanifest/argocd-demo/kustomize-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: sheru
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
