name: 080-resusable-workflow-caller

on:
  push:
    branches: none # [ main ]
  pull_request:
    branches: none # [ main ]
  workflow_dispatch:

jobs:
  call-workflow-A:
    uses: ./.github/workflows/080-reusable-workflow-called.yml
    with:
      username: Houssem

  call-workflow-B:
    uses: ./.github/workflows/080-reusable-workflow-called.yml
    with:
      username: Dellai
