name: 3-actions-ci-cd-aks-tf-backend

on:
  push:
    branches: none # [ main ]
  pull_request:
    branches:  none # [ release ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  LOCATION: eastus
  INFRA_RESOURCE_GROUP: maa2
  TF_STATE_STORAGE_ACCOUNT_NAME: back
  TF_STATE_CONTAINER_NAME: tfstate
  TF_STATE_FILE_NAME: tfstate
  TF_STATE_ACCESS_KEY: "" # will be set later
  DOCKER_REPOSITORY: harishnarang2018
  IMAGE_NAME: kopal
  IMAGE_TAG: ${{ github.run_number }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }} 
  AKS_RESOURCE_GROUP: aks-102-rg
  AKS_NAME: aks-102
  ACR_NAME: acrforaks102
jobs:
  build-and-deploy:
    name: Build and deploy into AKS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: hashicorp/setup-terraform@v1
      name: Setup Terraform
      with:
        terraform_version: 1.7.5 # 1.0.6 #
 
    - name: Terraform fmt
      id: fmt
      run: terraform fmt
      working-directory: infra11
      continue-on-error: true
 
    - name: Terraform Init (Azure Backend)
      id: init
      run: | 
        terraform init
          -backend-config="resource_group_name=back" \
          -backend-config="storage_account_name=tt421" \
          -backend-config="container_name=tfstate" \
          -backend-config="key=terraform1.tfstate"
      working-directory: infra1/
 
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      working-directory: infra1
 
    - name: Terraform Plan
      id: plan
      run: terraform plan -out out.plan -var-file="terraform.tfvars"
      working-directory: infra1
      continue-on-error: true
 
    - name: Terraform Apply
      # if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: terraform apply -auto-approve out.plan
      working-directory: infra1
