name: aks4

on:
  push:
    branches: none # [ main ]
    paths: .github/workflows/aks3.yml
  pull_request:
    branches:  none # [ release ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatchi:

permissions:
  id-token: write
  contents: read

env:
  LOCATION: eastus2
  INFRA_RESOURCE_GROUP: tutorial
  TF_STATE_STORAGE_ACCOUNT_NAME: back
  TF_STATE_CONTAINER_NAME: tfstate
  TF_STATE_FILE_NAME: tfstate
  TF_STATE_ACCESS_KEY: "" # will be set later
  DOCKER_REPOSITORY: harishnarang2018
  IMAGE_NAME: kopal
  IMAGE_TAG: ${{ github.run_number }}
  ARM_USE_OIDC: true
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AKS_RESOURCE_GROUP: tutorial
  AKS_NAME: aks1
  ACR_NAME: acr047
jobs:
  build-and-deploy:
    name: Build and deploy into AKS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
     
    - uses: hashicorp/setup-terraform@v1
      name: Setup Terraform
      with:
        terraform_version: 1.7.5 # 1.0.6 #
 
    - name: Terraform fmt
      id: fmt
      run: terraform fmt
      working-directory: infra1
      continue-on-error: true
 
    - name: Terraform Init (Azure Backend)
      id: init
      run: | 
        terraform init \
          -backend-config="resource_group_name=back" \
          -backend-config="storage_account_name=tt421" \
          -backend-config="container_name=tfstate" \
          -backend-config="key=terraform4.tfstate"
      working-directory: infra1
 
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      working-directory: infra1
 
    - name: Terraform Plan
      id: plan
      run: terraform plan -out out.plan -var-file="terraform.tfvars"
      working-directory: infra1
      continue-on-error: true
 
    - name: Terraform Apply
      # if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: terraform apply -auto-approve out.plan
      working-directory: infra1

    - name: Build Docker Image
      working-directory: .
      run:
        docker build ./MvcApp/ --file ./MvcApp/Dockerfile --tag $DOCKER_REPOSITORY/$IMAGE_NAME:$GITHUB_RUN_NUMBER  --no-cache
  
    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_REPOSITORY_PASSWORD }}" | docker login -u $DOCKER_REPOSITORY --password-stdin

    - name: Push Image to Docker Hub
      run:
        docker push $DOCKER_REPOSITORY/$IMAGE_NAME:$GITHUB_RUN_NUMBER

    - name: Replace Image Name in Deployment
      uses: cschleiden/replace-tokens@v1
      with:
        files: '["kubernetes/*.yaml"]'
        tokenPrefix: __ # optional, default is #{
        tokenSuffix: __ # optional, default is }#
      env:
        DOCKER_REPOSITORY: ${{ env.DOCKER_REPOSITORY }}
        IMAGE_NAME: ${{ env.IMAGE_NAME }}
        IMAGE_TAG: ${{ env.IMAGE_TAG }}

    # Set the target AKS cluster.
    - uses: Azure/aks-set-context@v1
      with:
        cluster-name: ${{ env.AKS_NAME }}
        resource-group: ${{ env.AKS_RESOURCE_GROUP }}

    - uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          kubernetes/nginx1.yaml
