name: AWS Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:  

permissions:
  id-token: write   # REQUIRED for OIDC
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::160071257600:role/github-actions-role
          aws-region: us-east-1

      - name: Verify identity
        run: aws sts get-caller-identity
