name: Terraform Destroy (No Environment)

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read


jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::160071257600:role/github-actions-role
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: | 
          terraform init -input=false \
            -backend-config="bucket=karantest2026" \
            -backend-config="key=eks/github-actions/terraform.tfstate" \
            -backend-config="region=us-east-1"

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
