name: Create Azure INSTALLATION With Terraform1
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
jobs:
  AKS-Cluster-Deployment:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./AKS
	  env:
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}	
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
       
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
     
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7  # Specify the Terraform version 

      - name: Terraform Init
        id: init
        run: terraform init
 
     
      - name: Terraform Validate
        id: validate
        run: terraform validate
       
      - name: Terraform Plan
        id: plan
        run: terraform plan -out tfplan
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1
  
      - name: Terraform Apply
        run: terraform apply -auto-approve
                  
      - name: Terraform Output
        run: terraform output
